server:
  port: 1987
spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a:
      path: /api-user/**
      serviceId: cloud-service-consumer

# set hystrix timeout to 5 seconds in order to avoid the failure of the first request through zuul
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1988/eureka/
