server:
  port: 1987
spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a:
      path: /api-user/**
      serviceId: cloud-service-consumer

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

# to force zuul to stop timing out long-running requests
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.101:1988/eureka/
