server:
  port: 1987
spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a:
      path: /api-user/**
      serviceId: cloud-service-consumer

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1988/eureka/
