server:
  port: 1987
spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a:
      path: /api-user/**
      serviceId: cloud-service-consumer

# set hystrix timeout to 5 seconds in order to avoid the failure of the first request through zuul
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 100000
# to forbid request time out
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

# to force zuul to stop timing out long-running requests
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1988/eureka/
