server:
  port: 1987
spring:
  application:
    name: api-gateway
zuul:
  routes:
    consumer:
      path: /consumer/**
      serviceId: cloud-service-consumer
    users:
      path: /users/**
      serviceId: cloud-service-provider

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

# to force zuul to stop timing out long-running requests
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.1.100:8761/eureka/
      defaultZone: http://192.168.25.128:8761/eureka/
security:
  basic:
    enabled: false
management:
#  context-path: /${spring.application.name}}
  security:
    enabled: false